org.gradle.jvmargs=-Xmx20480m
org.gradle.java.home=/Users/mihailbelyj/Library/Java/JavaVirtualMachines/corretto-17.0.15/Contents/Home
org.gradle.parallel=true
android.useAndroidX=true
android.enableJetifier=false
android.defaults.buildFeatures.resValues=false
android.defaults.buildFeatures.shaders=false
xcodeproj=./ios-app
kotlin.native.disableCompilerDaemon = true
org.jetbrains.compose.experimental.jscanvas.enabled=true
org.jetbrains.compose.experimental.wasm.enabled=true
kotlin.native.ignoreDisabledTargets=true
